name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'
    - name: Lint
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=./.*
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install BlueZ development headers
      run: |
        sudo apt-get update
        sudo apt-get install -y libbluetooth-dev
    - name: Install package
      run: pip install .
    - name: Run tests
      run: python -m unittest discover -s tests -v

  build-wheel:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        pip install build
        python -m build --wheel
    - name: Upload wheel
      uses: actions/upload-artifact@v7
      with:
        name: dist-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist

  build-wheel-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux_2_28_x86_64
        with:
          python-versions: 'cp310-cp310 cp311-cp311 cp312-cp312 cp313-cp313 cp314-cp314'
          system-packages: 'bluez-libs-devel'
      - name: Upload wheel
        uses: actions/upload-artifact@v7
        with:
          name: dist-linux-x86_64
          path: dist

  package_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'
      - name: Make source distribution
        run: |
          pip install build
          python -m build --sdist
      - name: Upload source distribution
        uses: actions/upload-artifact@v7
        with:
          name: dist-sdist
          path: dist
